import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Wrapper = styled.div`
  margin: 20px;

  a {
    color: #0070f3;
    font-weight: 500;
  }
`;

const Title = styled.h1`
  font-weight: 800;
`;

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Karl Hobley</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Title>
          Karl Hobley (aka. <span title="KArl EDward ROss HObley">kaedroho</span>)
        </Title>
        <ul>
          <li><a href="http://github.com/kaedroho">GitHub</a></li>
          <li><a href="https://twitter.com/kaedroho">Twitter</a></li>
          <li><a href="https://instagram.com/kaedroho">Instagram</a></li>
        </ul>
      </main>
    </Wrapper>
  )
}

export default Home
