import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Wrapper = styled.div`
  max-width: 900px;
  padding: 20px;
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
`;

const Title = styled.h1`
  font-size: 1.5em;
  font-weight: 700;
  margin: 0;
  color: #f5cb73;
`;

const LinksList = styled.ul`
  display: flex;
  flex-flow: column nowrap;
  gap: 0.1em;
  padding-left: 1em;

  > li::marker {
    color: #d4d4d4;
  }
`;

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Karl Hobley</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <header>
          <Title>
            Karl Hobley
          </Title>
      </header>

      <main>
        <LinksList>
          <li><a href="http://github.com/kaedroho">GitHub</a></li>
          <li><a href="https://twitter.com/kaedroho">Twitter</a></li>
          <li><a href="https://instagram.com/kaedroho">Instagram</a></li>
        </LinksList>
      </main>
    </Wrapper>
  )
}

export default Home
